// Code generated by Kitex v0.4.4. DO NOT EDIT.

package helloservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	example "github.com/li-jin-gou/kitex-server-demo/kitex_gen/hello/example"
)

func serviceInfo() *kitex.ServiceInfo {
	return helloServiceServiceInfo
}

var helloServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "HelloService"
	handlerType := (*example.HelloService)(nil)
	methods := map[string]kitex.MethodInfo{
		"HelloMethod1": kitex.NewMethodInfo(helloMethod1Handler, newHelloServiceHelloMethod1Args, newHelloServiceHelloMethod1Result, false),
		"HelloMethod2": kitex.NewMethodInfo(helloMethod2Handler, newHelloServiceHelloMethod2Args, newHelloServiceHelloMethod2Result, false),
		"HelloMethod3": kitex.NewMethodInfo(helloMethod3Handler, newHelloServiceHelloMethod3Args, newHelloServiceHelloMethod3Result, false),
	}
	extra := map[string]interface{}{
		"PackageName": "example",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func helloMethod1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*example.HelloServiceHelloMethod1Args)
	realResult := result.(*example.HelloServiceHelloMethod1Result)
	success, err := handler.(example.HelloService).HelloMethod1(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceHelloMethod1Args() interface{} {
	return example.NewHelloServiceHelloMethod1Args()
}

func newHelloServiceHelloMethod1Result() interface{} {
	return example.NewHelloServiceHelloMethod1Result()
}

func helloMethod2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*example.HelloServiceHelloMethod2Args)
	realResult := result.(*example.HelloServiceHelloMethod2Result)
	success, err := handler.(example.HelloService).HelloMethod2(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceHelloMethod2Args() interface{} {
	return example.NewHelloServiceHelloMethod2Args()
}

func newHelloServiceHelloMethod2Result() interface{} {
	return example.NewHelloServiceHelloMethod2Result()
}

func helloMethod3Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*example.HelloServiceHelloMethod3Args)
	realResult := result.(*example.HelloServiceHelloMethod3Result)
	success, err := handler.(example.HelloService).HelloMethod3(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceHelloMethod3Args() interface{} {
	return example.NewHelloServiceHelloMethod3Args()
}

func newHelloServiceHelloMethod3Result() interface{} {
	return example.NewHelloServiceHelloMethod3Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) HelloMethod1(ctx context.Context, request *example.HelloReq) (r *example.HelloResp, err error) {
	var _args example.HelloServiceHelloMethod1Args
	_args.Request = request
	var _result example.HelloServiceHelloMethod1Result
	if err = p.c.Call(ctx, "HelloMethod1", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HelloMethod2(ctx context.Context, request *example.HelloReq) (r *example.HelloResp, err error) {
	var _args example.HelloServiceHelloMethod2Args
	_args.Request = request
	var _result example.HelloServiceHelloMethod2Result
	if err = p.c.Call(ctx, "HelloMethod2", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HelloMethod3(ctx context.Context, request *example.HelloReq) (r *example.HelloResp, err error) {
	var _args example.HelloServiceHelloMethod3Args
	_args.Request = request
	var _result example.HelloServiceHelloMethod3Result
	if err = p.c.Call(ctx, "HelloMethod3", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
